/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelotabla.vista;

import modelotabla.database.UsuarioConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilichh1
 */
public class Usuario extends javax.swing.JFrame {
    private String parametroBusqueda = null;

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        try {
            this.getUsersData();
        } catch(Exception ex) {
            System.out.println("Exception: " +ex.getMessage());
            System.out.println("NO SE PUDIERON INICIALIZAR LOS DATOS.");
        }
    }
    
    private void getUsersData() throws SQLException {
        String sqlQuery;
        if (    parametroBusqueda != null
            && !parametroBusqueda.isEmpty()
            && !parametroBusqueda.isBlank() ) // Validar el string
        {
            // Solo buscamos por nombres y apellidos
            sqlQuery = "SELECT * FROM usuario"
                    + " WHERE nombres LIKE '%"+parametroBusqueda+"%'"
                    + " OR apellidos LIKE '%"+parametroBusqueda+"%';";
        } else {
            sqlQuery = "SELECT * FROM usuario;";
        }
        ResultSet rs = this.makeQuery(sqlQuery);
        int columnCount = rs.getMetaData().getColumnCount();
        Vector<String> columnNames = new Vector<String>();
        for (int i = 0; i < columnCount; i++) {
            columnNames.addElement(rs.getMetaData().getColumnName(i+1));
        }
        
        Vector<Vector> filas = new Vector<>();
        while (rs.next()) {
            Vector<String> tupla = new Vector<>();
            for (int i = 0; i < columnCount; i++) {
                tupla.addElement(rs.getString(i+1));
            }
            filas.addElement(tupla);
        }
        this.createAndSetTableModel(filas, columnNames);
    }
    
    private ResultSet makeQuery(String sqlQuery) {
        try {
            Connection conexion = UsuarioConnection.getDataBaseConnection();
            Statement stmt = conexion.createStatement();
            stmt.execute(sqlQuery);
            return stmt.getResultSet();
        } catch (SQLException ex) {
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("LA CONSULTA ES INCORRECTA");
        }
        return null;
    }
    
    private void createAndSetTableModel(Vector data, Vector columnNames) {
        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        busquedaTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(busquedaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(busquedaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parametroBusqueda = busquedaTXT.getText();
        try {
            this.getUsersData();
        } catch (SQLException ex) {
            System.out.println("SQLException "+ex);
            System.out.println("NO SE PUEDO CONSULTAR LA BD.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedaTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}